language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements/development.txt"
# command to run tests
script: cd webapp && ./runtests.sh
