language: python
sudo: false
python:
  - "3.6"
# command to install dependencies
install:
  - "pip3 install -r requirements/development.txt"
# command to run tests
script: cd webapp && ./runtests.sh && flake8 --exclude migrations,settings
